// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO8UuwvAPMZ7LdiGzuR4jNLXgQ4Qfwsmg',
    appId: '1:98863432864:web:5fcc80ba6893f021d6f5c5',
    messagingSenderId: '98863432864',
    projectId: 'getblogs-c0af2',
    authDomain: 'getblogs-c0af2.firebaseapp.com',
    storageBucket: 'getblogs-c0af2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl5wu3Jx6LMTgjT0eucZnO9m_gXsUgmgI',
    appId: '1:98863432864:android:84a4f7d633852a41d6f5c5',
    messagingSenderId: '98863432864',
    projectId: 'getblogs-c0af2',
    storageBucket: 'getblogs-c0af2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDprfGxbFw-pbdDhQvNCZQ3FGWlgi0dixI',
    appId: '1:98863432864:ios:9c37796cb5a88aebd6f5c5',
    messagingSenderId: '98863432864',
    projectId: 'getblogs-c0af2',
    storageBucket: 'getblogs-c0af2.appspot.com',
    iosBundleId: 'com.example.getblogs',
  );
}
